=== Eveler/dmsis/declar-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by TeaM DJiNN (TeaM DJiNN) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:ns1="urn://augo/smev/uslugi/1.0.0" targetNamespace="urn://augo/smev/uslugi/1.0.0" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="declar">
		<xs:annotation>
			<xs:documentation>Информация по обращению заявителя</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="declar_number" type="xs:string">
					<xs:annotation>
						<xs:documentation>№ дела (обращения)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="service" type="xs:string">
					<xs:annotation>
						<xs:documentation>Код (номер) услуги</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="register_date" type="xs:date">
					<xs:annotation>
						<xs:documentation>Дата регистрации запроса</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="end_date" type="xs:date">
					<xs:annotation>
						<xs:documentation>Плановый срок предоставления услуги</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="object_address" type="ns1:Address" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Место нахождения объекта услуги</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="AppliedDocument" type="ns1:AppliedDocument" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Приложенный документ</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="legal_entity" type="ns1:LegalEntity" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Заявитель - ЮЛ/ИП</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="person" type="ns1:Individual" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Заявитель - ФЛ</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:choice>
				<xs:element name="confidant" type="ns1:Individual" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Доверенное лицо</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Param" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Дополнительный параметр</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required" type="xs:string">
									<xs:annotation>
										<xs:documentation>тип значения параметра: Boolean или Integer или Double или Date или DateTime или String</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="id" use="required" type="xs:string">
									<xs:annotation>
										<xs:documentation>внутренний идентификатор параметра (только цифры и латинсуие символы, начинается с символа)</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="label" type="xs:string">
									<xs:annotation>
										<xs:documentation>читаемое человеком наименование параметра</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="rowNumber" type="xs:string">
									<xs:annotation>
										<xs:documentation>если значение параметра - массив, количество строк массива</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="colNumber" type="xs:string">
									<xs:annotation>
										<xs:documentation>если значение параметра - массив, количество столбцов массива</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="rowDelimiter" type="xs:string">
									<xs:annotation>
										<xs:documentation>символ - разделитель строк массива</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="colDelimiter" type="xs:string">
									<xs:annotation>
										<xs:documentation>символ - разделитель колонок массива</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="AgentType">
		<xs:annotation>
			<xs:documentation>Тип заявителя</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>Юридическое лицо/Индивидуальный предприниматель</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Физическое лицо</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Sex">
		<xs:annotation>
			<xs:documentation>Пол</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Муж"/>
			<xs:enumeration value="Жен"/>
			<xs:enumeration value=""/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Address">
		<xs:annotation>
			<xs:documentation>Адрес</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Postal_Code" type="ns1:s6" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Почтовый индекс</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Region" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Регион</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="District" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Район</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="City" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Муниципальное образование</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Urban_District" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Городской район</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Soviet_Village" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Сельсовет</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Locality" type="xs:string" default="Уссурийск">
				<xs:annotation>
					<xs:documentation>Населенный пункт</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:choice>
				<xs:sequence minOccurs="0">
					<xs:element name="Street" type="xs:string">
						<xs:annotation>
							<xs:documentation>Улица</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="House" type="xs:string">
						<xs:annotation>
							<xs:documentation>Дом</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:element name="Reference_point" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Ориентир</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:element name="Housing" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Корпус</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Building" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Строение</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Apartment" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Квартира</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="s6">
		<xs:annotation>
			<xs:documentation>строка с ограничением длины до 6 знаков</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="6"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="s10">
		<xs:annotation>
			<xs:documentation>строка с ограничением длины до 10 знаков</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="s50">
		<xs:annotation>
			<xs:documentation>строка с ограничением длины до 50 знаков</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="s120">
		<xs:annotation>
			<xs:documentation>строка с ограничением длины до 120 знаков</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="120"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="s1024">
		<xs:annotation>
			<xs:documentation>строка с ограничением длины до 1024 знаков</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="1024"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AppliedDocument">
		<xs:annotation>
			<xs:documentation>Приложенный документ</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="title" type="ns1:s1024">
				<xs:annotation>
					<xs:documentation>Наименование документа</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="number" type="ns1:s50">
				<xs:annotation>
					<xs:documentation>Номер документа</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="date" type="xs:date">
				<xs:annotation>
					<xs:documentation>Дата документа</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="valid_until" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Действителен до</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="file_name" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Имя файла документа</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="url" type="xs:string">
				<xs:annotation>
					<xs:documentation>Прямая ссылка на файл. Поддерживаются только пртоколы HTTP, FTP</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="url_valid_until" type="xs:dateTime" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Срок действия ссылки на файл, до</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LegalEntity">
		<xs:annotation>
			<xs:documentation>Юридическое лицо/Индивидуальный предприниматель</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>Краткое наименование ЮЛ</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="full_name" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Полное наименование ЮЛ</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="inn" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>ИНН</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="kpp" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>КПП</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="address" type="ns1:Address">
				<xs:annotation>
					<xs:documentation>Юридический адресс</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ogrn" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>ОГРН</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="taxRegDoc" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Данные документа о постановке заявителя на учет в налоговом органе</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="govRegDoc" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Номер документа, подтверждающего факт внесения сведений в единый государственный реестр</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="govRegDate" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Дата государственной регистрации юридического лица</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="phone" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>телефон</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Адрес электронной почты</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="bossFio" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Фамилия И.О. руководителя</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="buhFio" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Фамилия И.О. главного бухгалтера</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="bank" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Наименование банка</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="bankAccount" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Банковский счёт</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="lastCtrlDate" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Дата проведения последней плановой проверки</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="opf" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Организационно-правовая форма</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="govRegOgv" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Регистрирующий государственный орган</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="person" type="ns1:Individual" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Представитель юридического лица</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Individual">
		<xs:annotation>
			<xs:documentation>Физическое лицо</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="surname" type="xs:string">
				<xs:annotation>
					<xs:documentation>Фамилия</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="first_name" type="xs:string">
				<xs:annotation>
					<xs:documentation>Имя</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="patronymic" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Отчество</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="address" type="ns1:Address">
				<xs:annotation>
					<xs:documentation>Адрес регистрации</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="fact_address" type="ns1:Address" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Адрес фактического проживания</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Адрес электронной почты</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="birthdate" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Дата рождения</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="passport_serial" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Серия паспорта</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="passport_number" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>№ паспорта</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="passport_agency" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Кем выдан паспорт</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="passport_date" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Дата выдачи паспорта</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="phone" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>телефон</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="inn" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>ИНН</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sex" type="ns1:Sex" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Пол</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="snils" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>СНИЛС</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="requestResponse">
		<xs:annotation>
			<xs:documentation>Ответ на запрос</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="declar_number" type="xs:string">
				<xs:annotation>
					<xs:documentation>№ дела (обращения)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="register_date" type="xs:date">
				<xs:annotation>
					<xs:documentation>Дата регистрации запроса</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="result">
				<xs:annotation>
					<xs:documentation>Результат регистрации запроса</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ACCEPTED">
							<xs:annotation>
								<xs:documentation>Принято в работу</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="INTERMEDIATE">
							<xs:annotation>
								<xs:documentation>Промежуточный ответ</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="INFO">
							<xs:annotation>
								<xs:documentation>Информация об изменении статуса обработки запроса</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="ERROR">
							<xs:annotation>
								<xs:documentation>Ошибка обработки запроса</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="FINAL">
							<xs:annotation>
								<xs:documentation>Окончательный результат</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="text" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Сообщение пользователю</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AppliedDocument" type="ns1:AppliedDocument" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Документ для выдачи заявителю</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="requestResponse" type="ns1:requestResponse">
		<xs:annotation>
			<xs:documentation>Ответ на запрос</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== Eveler/dmsis/tests/Response2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:requestResponse xsi:schemaLocation="urn://augo/smev/uslugi/1.0.0 declar-1.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="urn://augo/smev/uslugi/1.0.0">
                           <ns1:declar_number>23156/564/5611Д</ns1:declar_number>
                           <ns1:register_date>2008-09-29</ns1:register_date>
                           <ns1:result>INTERMEDIATE</ns1:result>
                          <ns1:AppliedDocument>
                            <ns1:title>Уведомление</ns1:title>
                            <ns1:number>08-65/2569</ns1:number>
                            <ns1:date>2008-09-30</ns1:date>
                            <ns1:url>https://123.45.67.89/download/AE4567BC</ns1:url>
                            <ns1:url_valid_until>2008-10-03T01:41:17.783+04:00</ns1:url_valid_until>
                          </ns1:AppliedDocument>
</ns1:requestResponse>

=== Eveler/dmsis/tests/Request.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:declar xsi:schemaLocation="urn://augo/smev/uslugi/1.0.0 declar-1.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="urn://augo/smev/uslugi/1.0.0">
	<ns1:declar_number>23156/564/5611Д</ns1:declar_number>
	<ns1:service>13.2</ns1:service>
	<ns1:register_date>2008-09-29</ns1:register_date>
	<ns1:end_date>2014-09-19</ns1:end_date>
	<ns1:AppliedDocument>
		<ns1:title>Заявление</ns1:title>
		<ns1:number>б/н</ns1:number>
		<ns1:date>2008-09-29</ns1:date>
		<ns1:url>https://12.345.67.89/download/AE4567BC</ns1:url>
		<ns1:url_valid_until>2008-09-30T17:41:17.783+04:00</ns1:url_valid_until>
	</ns1:AppliedDocument>
	<ns1:legal_entity>
		<ns1:name>Краткое наименование</ns1:name>
		<ns1:full_name>Полное наименование</ns1:full_name>
		<ns1:inn>25110201</ns1:inn>
		<ns1:kpp>251136652</ns1:kpp>
		<ns1:address>
			<ns1:Postal_Code>692500</ns1:Postal_Code>
			<ns1:Region>Приморский край</ns1:Region>
			<ns1:Locality>г.Уссурийск</ns1:Locality>
			<ns1:Street>ул.Ленина</ns1:Street>
			<ns1:House>101</ns1:House>
		</ns1:address>
		<ns1:ogrn>566214</ns1:ogrn>
		<ns1:phone>8 (4234) 319-303</ns1:phone>
		<ns1:email>ioib@adm-ussuriisk.ru</ns1:email>
		<ns1:bossFio>Фамилия Имя Отчество</ns1:bossFio>
		<ns1:buhFio>Фамилия Имя Отчество</ns1:buhFio>
		<ns1:bank>Отделение №1 по ПК в г.Владивосток</ns1:bank>
		<ns1:bankAccount>52300000000446</ns1:bankAccount>
		<ns1:person>
			<ns1:surname>Фамилия</ns1:surname>
			<ns1:first_name>Имя</ns1:first_name>
			<ns1:patronymic>Отчество</ns1:patronymic>
			<ns1:address>
				<ns1:Locality>г.Уссурийск</ns1:Locality>
				<ns1:Street>пр.Блюхера</ns1:Street>
				<ns1:House>1Б</ns1:House>
				<ns1:Apartment>26</ns1:Apartment>
			</ns1:address>
			<ns1:phone>89241234567</ns1:phone>
		</ns1:person>
	</ns1:legal_entity>
	<ns1:person>
		<ns1:surname>Бендер</ns1:surname>
		<ns1:first_name>Остап</ns1:first_name>
		<ns1:patronymic>Ибрагимович</ns1:patronymic>
		<ns1:address>
			<ns1:Locality>г.Уссурийск</ns1:Locality>
			<ns1:Street>ул.Некрасова</ns1:Street>
			<ns1:House>91</ns1:House>
			<ns1:Housing>А</ns1:Housing>
			<ns1:Apartment>34</ns1:Apartment>
		</ns1:address>
		<ns1:passport_serial>0502</ns1:passport_serial>
		<ns1:passport_number>554654</ns1:passport_number>
		<ns1:passport_agency>РОВД г.Уссурийск</ns1:passport_agency>
		<ns1:passport_date>2019-08-19</ns1:passport_date>
		<ns1:phone>89021234567</ns1:phone>
		<ns1:sex>Муж</ns1:sex>
	</ns1:person>
	<ns1:confidant>
		<ns1:surname>Фамилия</ns1:surname>
		<ns1:first_name>Имя</ns1:first_name>
		<ns1:address>
			<ns1:Locality>г.Уссурийск</ns1:Locality>
			<ns1:Street>ул.Ленина</ns1:Street>
			<ns1:House>95</ns1:House>
			<ns1:Housing>Б</ns1:Housing>
			<ns1:Apartment>59</ns1:Apartment>
		</ns1:address>
		<ns1:phone>89141234567</ns1:phone>
	</ns1:confidant>
	<ns1:Param type="String" id="object_type" label="Вид объекта услуги">Значение</ns1:Param>
</ns1:declar>
